spring.data.mongodb.uri=mongodb+srv://username:password@cluster0.fku8p.mongodb.net/M001?authSource=admin&replicaSet=Cluster0-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true
spring.data.mongodb.database=paymentdb
